-- Default password: LiveOaks2026!
-- Members should be prompted to change this on first login

INSERT INTO users (first_name, last_name, email, password_hash, role, status) VALUES
('Art',        'Acosta',        'artacos15@gmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Karissa',    'Adams',         'kchabner@gmail.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('David',      'Adelstein',     'dsadelstein@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Bob',        'Altman',        'bob@mcsxperts.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Mustapha',   'Baha',          'mbaha@att.net',                     '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('John',       'Bea',           'jgbea@msn.com',                     '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Matthew',    'Bickell',       'mdbickell@gmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Oren',       'Bitan',         'orenbitan@gmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Rick',       'Brandley',      'rickb@georgesshowroom.com',         '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jordan',     'Brown',         'jordanbrown2023@gmail.com',         '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Christyne',  'Burdett',       'christyne.ink@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Paul',       'Cabot',         'paul.cabot@gmail.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('D. Scott',   'Carlton',       'dsc262001@yahoo.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Thomas',     'Carter',        'tmc505@me.com',                     '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Art',        'Chen',          'arthurkchen@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('David',      'Chian',         'davechian@yahoo.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Fran',       'Cholko',        'fcholko1945@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Dianne',     'Ciulla',        'ciaociulla@earthlink.net',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Chris',      'Condit',        'Chriscondit1@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Terence',    'Cuff',          'tcuff@loeb.com',                    '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Robert',     'Curtiss',       'arcurtiss639@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('YunYun',     'Dai',           'daiyunyun@hotmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Arman',      'Davtyan',       'adavtyan_2000@yahoo.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Dave',       'de Csepel',     'dave@veritasri.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Sonny',      'DeGuzman',      'sonnyd6@mac.com',                   '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Stephanie',  'Dencik',        'stephanie@dencik.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Warren',     'Elgort',        'elgort@usc.edu',                    '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Laura',      'Ferguson',      'lauraferguson77@gmail.com',         '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Gabe',       'Fitch',         'gabefitch@yahoo.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Kevin',      'Frasier',       'kgf@h-finc.com',                    '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Joanna',     'Gardner',       'Joannag64@gmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Peter',      'Gertmenian',    'pgertmenian@gertmenian.com',        '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Stephanie',  'Ginn',          'stephaniesginn@gmail.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Vanessa',    'Godson',        'vanessagodson@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Stephen',    'Godwin',        'sjgodwin@me.com',                   '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Amber',      'Haley',         'amberhaley@me.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Matt',       'Hansen',        'matthewshansen@gmail.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Michael',    'Henderson',     'mchenderson92@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Fernando',   'Hernandez',     'Fernalma096@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jack',       'Horne',         'jacksonhorne@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Greg',       'Howard',        'greg@howardsmail.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'admin',  'active'),
('Angela',     'Hsu',           'angelahsumd@hotmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Shihyen',    'Hsu',           'shihyenh@hotmail.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Chun Ming',  'Huang',         'chunming76@gmail.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Shirley',    'Jagels',        'mrsshirleyjagels@gmail.com',        '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jerri',      'Johnson',       'jjohnson@murchisonlaw.com',         '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Kristofer',  'Johnson',       'kristofer.j.johnson@gmail.com',     '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Amy Davis',  'Jones',         'amydavisjones@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Mark',       'Kane',          'mark.c.kane@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Dan',        'Kanemoto',      'dkanemoto@aol.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Sajan',      'Kashyap',       'sajan@kashyaplaw.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('William',    'Ko',            'williamkois@yahoo.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Sarah',      'Krappman',      'sarah@sarahrogersestates.com',      '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jesse',      'Kreger',        'jessemkreger@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Leonard',    'Lee',           'Leonardlee73@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Adam',       'Ludwin',        'aludwin@gmail.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Kim',        'Luk',           'Kimluk3@gmail.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Kevin',      'Lutz',          'kevinmlutz@gmail.com',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Hilary',     'MacGregor',     'hilaryemacgregor@gmail.com',        '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jennifer',   'Madden',        'jenmadden@me.com',                  '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Cecil',      'Mamiit',        'cvmamiit@gmail.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Sean',       'Manion',        'seancmanion@hotmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Steve',      'Marrs',         'stevetriciamarrs@gmail.com',        '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Stephen',    'Marsh',         'stevesuemarsh@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Darrell',    'Mavis',         'persuasivespeaking@gmail.com',      '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Harper',     'McDonald',      'harpermcd@yahoo.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Mark',       'Messana',       'messanamark@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Wade',       'Metzler',       'wade.metzler@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Bill',       'Michels',       'bill.j.michels@gmail.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Ed',         'Morales',       'edwardjmorales@aol.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Andrea',     'Moriarty',      'andibeall@yahoo.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Eric',       'Neu',           'neueric@hotmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Brian',      'Newhall',       'bnewhall@oxy.edu',                  '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Khanh',      'Oberley',       'khanh.oberley@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Michael',    'Ortiz',         'mbortiz8@gmail.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Thomas',     'Ortiz',         'ortiz1t@earthlink.net',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Linda',      'Park',          'lindapark333@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Christine',  'Pedroza',       'Cpedroza@colepedroza.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Charlie',    'Perry',         'davidcharlesinc@yahoo.com',         '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Julian',     'Petrillo',      'julian.petrillo@icloud.com',        '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('John',       'Pettersson',    'johnpettersson@yahoo.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('John',       'Proulx',        'john@johnproulx.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Nancy',      'Ray',           'nancychenray@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jed',        'Reagan',        'jedreagan@gmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Duane',      'Rhetta',        'duane.rhetta@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Roberto',    'Roizenblatt',   'robertoeyemd@gmail.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Jeffrey',    'Rosenberg',     'roseyyy@gmail.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Michelle',   'Round',         'choniqueen@aol.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Joyce',      'Sakonju',       'joycesakonju@yahoo.com',            '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Marianne',   'Samson',        'wahlen63samson@gmail.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Mindy',      'Sato',          'satomommy@aol.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Leilani',    'Scholtz',       'leilanis515@gmail.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Blair',      'Slattery',      'blairslattery@hotmail.com',         '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Paul',       'Stern',         'paul.stern@att.net',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Dan',        'Takeyama',      'dtakeyama@yahoo.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Sen',        'Tan',           'tsk0555@gmail.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Keane',      'Tarrosa',       'Keane.Tarrosa@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Christopher','Tayback',       'cheztay@sbcglobal.net',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Katie',      'Tong',          'Ktong34@yahoo.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Myron',      'Tong',          'mjtsp@aol.com',                     '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Dhaval',     'Trivedi',       'loombam@yahoo.com',                 '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Ken',        'Van Amringe',   'kenvanam5@gmail.com',               '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Elizabeth',  'Walters',       'ewalters91108@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Michael',    'Williamson',    'eileenwilliamson@mac.com',          '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Pete',       'Wilson',        'petewilson@aol.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Scott',      'Winnie',        'scottwinnie10@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Doug',       'Yokomizo',      'dyokomizo@outlook.com',             '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('David',      'Younger',       'dyounger@pacbell.net',              '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Reno',       'Yu',            'renoyu@hotmail.com',                '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active'),
('Stephen',    'Zeiss',         'stephen.zeiss@gmail.com',           '$2a$10$/y2s6QfM2ChqhSfx/4DSW.fmz55aV3RBg.RqqJok.2/if7qKxoRL.', 'member', 'active')
ON CONFLICT (email) DO NOTHING;
