GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liveoaks;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liveoaks;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO liveoaks;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO liveoaks;
